{"uid":"33292fb500ca1eb3","name":"An uncaught error was detected outside of a test","fullName":"An uncaught error was detected outside of a test","historyId":"c59643030e1e776644fd5d1d6aa79cfc","time":{"start":1676564388294,"stop":1676564388456,"duration":162},"status":"failed","statusMessage":"The following error originated from your test code, not from Cypress.\n\n  > Invalid Version: \n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","statusTrace":"TypeError: The following error originated from your test code, not from Cypress.\n\n  > Invalid Version: \n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.\n    at new SemVer (http://localhost:36269/__cypress/tests?p=cypress/specs/1-createIndividualAccount-spec10.js:23325:11)\n    at compare (http://localhost:36269/__cypress/tests?p=cypress/specs/1-createIndividualAccount-spec10.js:23598:10)\n    at Function.gte (http://localhost:36269/__cypress/tests?p=cypress/specs/1-createIndividualAccount-spec10.js:23647:10)\n    at Object.eval (http://localhost:36269/__cypress/tests?p=cypress/specs/1-createIndividualAccount-spec10.js:24251:12)\n    at Object../node_modules/utf7/utf7.js (http://localhost:36269/__cypress/tests?p=cypress/specs/1-createIndividualAccount-spec10.js:24368:30)\n    at __webpack_require__ (http://localhost:36269/__cypress/tests?p=cypress/specs/1-createIndividualAccount-spec10.js:20:30)\n    at Object.eval (http://localhost:36269/__cypress/tests?p=cypress/specs/1-createIndividualAccount-spec10.js:17525:12)\n    at Object../node_modules/imap/lib/Connection.js (http://localhost:36269/__cypress/tests?p=cypress/specs/1-createIndividualAccount-spec10.js:19648:30)\n    at __webpack_require__ (http://localhost:36269/__cypress/tests?p=cypress/specs/1-createIndividualAccount-spec10.js:20:30)\n    at Object.eval (http://localhost:36269/__cypress/tests?p=cypress/specs/1-createIndividualAccount-spec10.js:14357:12)","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":9,"retriesStatusChange":false,"beforeStages":[],"testStage":{"status":"failed","statusMessage":"The following error originated from your test code, not from Cypress.\n\n  > Invalid Version: \n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","statusTrace":"TypeError: The following error originated from your test code, not from Cypress.\n\n  > Invalid Version: \n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.\n    at new SemVer (http://localhost:36269/__cypress/tests?p=cypress/specs/1-createIndividualAccount-spec10.js:23325:11)\n    at compare (http://localhost:36269/__cypress/tests?p=cypress/specs/1-createIndividualAccount-spec10.js:23598:10)\n    at Function.gte (http://localhost:36269/__cypress/tests?p=cypress/specs/1-createIndividualAccount-spec10.js:23647:10)\n    at Object.eval (http://localhost:36269/__cypress/tests?p=cypress/specs/1-createIndividualAccount-spec10.js:24251:12)\n    at Object../node_modules/utf7/utf7.js (http://localhost:36269/__cypress/tests?p=cypress/specs/1-createIndividualAccount-spec10.js:24368:30)\n    at __webpack_require__ (http://localhost:36269/__cypress/tests?p=cypress/specs/1-createIndividualAccount-spec10.js:20:30)\n    at Object.eval (http://localhost:36269/__cypress/tests?p=cypress/specs/1-createIndividualAccount-spec10.js:17525:12)\n    at Object../node_modules/imap/lib/Connection.js (http://localhost:36269/__cypress/tests?p=cypress/specs/1-createIndividualAccount-spec10.js:19648:30)\n    at __webpack_require__ (http://localhost:36269/__cypress/tests?p=cypress/specs/1-createIndividualAccount-spec10.js:20:30)\n    at Object.eval (http://localhost:36269/__cypress/tests?p=cypress/specs/1-createIndividualAccount-spec10.js:14357:12)","steps":[],"attachments":[{"uid":"cba62a66d09ae122","name":"1-createIndividualAccount-spec10.js:2023-02-16T16:19:48.335Z","source":"cba62a66d09ae122.png","type":"image/png","size":50744}],"parameters":[],"stepsCount":0,"attachmentsCount":1,"shouldDisplayMessage":true,"hasContent":true},"afterStages":[],"labels":[{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[{"uid":"aec71f53f612baec","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > Invalid Version: \n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1676564378770,"stop":1676564378924,"duration":154}},{"uid":"3214e1232b05ad57","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > Invalid Version: \n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1676564369204,"stop":1676564369366,"duration":162}},{"uid":"9193931ca8faa6a7","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > Invalid Version: \n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1676564359742,"stop":1676564359909,"duration":167}},{"uid":"cd0086e74dec0c51","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > Invalid Version: \n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1676564350423,"stop":1676564350589,"duration":166}},{"uid":"8de3646c28b5e1b6","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > Invalid Version: \n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1676564341072,"stop":1676564341217,"duration":145}},{"uid":"e4958969c14623c3","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > Invalid Version: \n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1676564331813,"stop":1676564331970,"duration":157}},{"uid":"bb9cd394de1f4c50","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > Invalid Version: \n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1676564322359,"stop":1676564322553,"duration":194}},{"uid":"eba2d7803ad84efa","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > Invalid Version: \n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1676564310846,"stop":1676564311039,"duration":193}},{"uid":"cb92029e46e4ccca","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > Invalid Version: \n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1676564300740,"stop":1676564300900,"duration":160}}],"categories":[{"name":"Product defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"33292fb500ca1eb3.json","parameterValues":[]}